### ISSUE TITLE
Some issue with the search

### ISSUE THREAD

**Issue by eti0** [rainbowintheshell/blackpearl#1]
Hey, I have no idea how your program works but look at the screenshot attached.
![screenshot from 2016-09-28 17-34-57](https://cloud.githubusercontent.com/assets/14180792/18920628/454ed112-85a2-11e6-9c3c-5eabf025bfd3.png)

Seems to be an error.

Have a nice day !

**Comment by aranciaga** [comment]
Hello, Thanks for send this issue. Can you try https://thepiratebay.se? This error seems to be due an ISP restriction.

**Comment by eti0** [comment]
Sorry, should've thought about that way before.
I'm just going to change my DNS ip's.

Thanks.

**Comment by eti0** [comment]
Actually, it doesn't really change anything.
I can still access thepiratebay.org, etc but it won't work via your program.

**Comment by aranciaga** [comment]
What is your node version? Also [check this](https://github.com/t3chnoboy/thepiratebay/issues/35). Your error is linked to thepiratebay library, which is used in blacksails

Keep me in touch please.

**Comment by eti0** [comment]
My npm version is 2.15.9.
Node version is 4.6.0.

Even after following the commands it still doesn't work.

**Comment by aranciaga** [comment]
Hi there, **thepiratebay** library seems to support only node >=6. So I wrote [my own library](https://github.com/rainbowintheshell/pirata). Hopefully now blackpearl supports your node version and more. Please update. Thanks!

**Comment by eti0** [comment]
Got a new error now.
![screenshot from 2016-09-29 20-35-22](https://cloud.githubusercontent.com/assets/14180792/18967123/5b077ad0-8684-11e6-85a1-a2ea351700a8.png)

I upgraded Node to 6 by the way.

**Comment by aranciaga** [comment]
Mmm, strange. I added error handling to blackpearl and pirata as well. If you don't mind try to update later again.
